[features]
seeds = false
skip-lint = false
[programs.localnet]
twine = "8u7SgCGmzZ7xjei8AzJ2PReBvkuxjSu8FBBrDnjM5GMZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
