[features]
seeds = false
skip-lint = false
[programs.localnet]
twine = "HsxDAhDzJH5nHtnTz1rk5jzHzygrzduA6wYaYZdmTQ7Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
