[features]
seeds = false
skip-lint = false
[programs.localnet]
twine = "HUHWYMoHQEsZtDEPJNxPXYWf1yMpUWGFKadD2V8QneAM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
